### ISSUE TITLE
postinstall failing

### ISSUE THREAD

**Issue by wilsonianb** [coilhq/tigerbeetle-node#20]
https://github.com/interledger/rafiki/runs/4168593074?check_suite_focus=true
```
tigerbeetle-node@npm:0.4.1 STDOUT Installing Zig 0.8.0 release build...
tigerbeetle-node@npm:0.4.1 STDOUT Downloading https://ziglang.org/builds/zig-linux-x86_64-0.9.0-dev.1599+008b0ec5e.tar.xz
tigerbeetle-node@npm:0.4.1 STDOUT https://ziglang.org/download/0.8.0/zig-linux-x86_64-0.8.0.tar.xz...
tigerbeetle-node@npm:0.4.1 STDOUT Extracting zig-linux-x86_64-0.8.0.tar.xz...
tigerbeetle-node@npm:0.4.1 STDOUT Installing zig-linux-x86_64-0.8.0 to 'zig' in current working directory...
tigerbeetle-node@npm:0.4.1 STDERR  40200K .......... .......... .......... .......... .....     100%  136M=0.4smv: cannot stat 'zig-linux-x86_64-0.8.0': No such file or directory
tigerbeetle-node@npm:0.4.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-92ba0a68/build.log)
```
It looks like it's trying to get 0.8.0 from a 0.9.0 url?
Not sure if updating the tigerbeetle submodule to include this will solve it
https://github.com/coilhq/tigerbeetle/commit/3f572cb446294ff35e79919a4a18bc99bbda8109

**Comment by DonChangfoot** [comment]
@wilsonianb I haven't been able to reproduce this locally. @matdehaast reran the pipeline and it passed. Feel free to post here if it happens again.

**Comment by wilsonianb** [comment]
:confused: Re-running also passed for me
https://github.com/interledger/rafiki/runs/4226819382?check_suite_focus=true
It looks like that `0.9.0-dev` url is back to `0.8.0`.
```
tigerbeetle-node@npm:0.4.1 STDOUT Installing Zig 0.8.0 release build...
tigerbeetle-node@npm:0.4.1 STDOUT Downloading https://ziglang.org/download/0.8.0/zig-linux-x86_64-0.8.0.tar.xz...
```
Hopefully it was just a blip. Thanks!
