### ISSUE TITLE
Understanding `Transfers.pending_id`

### ISSUE THREAD

**Issue by lewisdaly** [coilhq/tigerbeetle-node#28]
In the readme, the "Creating a transfer" has the following example:

```ts
const transfer = {
    id: 1n, // u128
    // Double-entry accounting:
    debit_account_id: 1n,  // u128
    credit_account_id: 2n, // u128
    // Opaque third-party identifier to link this transfer to an external entity:
    user_data: 0n, // u128  
    reserved: 0n, // u128
    // Timeout applicable for a pending/2-phase transfer:
    timeout: 0n, // u64, in nano-seconds.
    // Collection of accounts usually grouped by the currency: 
    // You can't transfer money between accounts with different ledgers:
    ledger: 720,  // u32, ledger for transfer (e.g. currency).
    // Chart of accounts code describing the reason for the transfer:
    code: 1,  // u16, (e.g. deposit, settlement)
    flags: 0, // u16
    amount: 10n, // u64
    timestamp: 0n, //u64, Reserved: This will be set by the server.
}
const errors = await client.createTransfers([transfer])
```

This fails typescript validation, since the `Transfer` type definition in in index.ts has: 
https://github.com/coilhq/tigerbeetle-node/blob/00296ed3b032d69aba0a1c1ff9b783e2814f5b86/src/index.ts#L85

And when I try ignoring the type errors I get the following error from the client:
```
Fatal Error: Error: pending_id must be a BigInt
    at /home/lew/developer/buoy/buoy-money/projects/demo-tb/node_modules/tigerbeetle-node/src/index.ts:299:17
    at new Promise (<anonymous>)
    at Object.createTransfers (/home/lew/developer/buoy/buoy-money/projects/demo-tb/node_modules/tigerbeetle-node/src/index.ts:289:12)
    at async main (/home/lew/developer/buoy/buoy-money/projects/demo-tb/scripts/_003_create_transfers.ts:40:18)
```

So I'm guessing that `pending_id` is required in `client.createTransfers()` -- so the types are correct, but the readme is wrong.

**Comment by jorangreef** [comment]
Thanks @lewisdaly — CC'ing @eatonphil

`pending_id` must be 0 for transfers that do not set `flags.post_pending_transfer` or `flags.void_pending_transfer`, and must be non-zero for transfers that are posting/voiding a pending transfer. i.e. `pending_id` is only set (non-zero) when a transfer references another previous transfer. However, if a transfer does not reference another, we still require that `pending_id` has a value of 0 to be explicit. This removes dimensionality in the type signatures.

**Comment by lewisdaly** [comment]
Thanks @jorangreef  - I think I've got it now.
