### ISSUE TITLE
install_zig.sh missing from package

### ISSUE THREAD

**Issue by wilsonianb** [coilhq/tigerbeetle-node#3]
Installing the package fails in `preinstall` because `scripts/install_zig.sh` isn't included in the `files` list in package.json

**Comment by jorangreef** [comment]
Thanks @wilsonianb ! There were also some issues where the install process would init the git submodule but without the client package being a git repo itself. We've moved the `git submodule` install steps into a `prepack` step instead, and also fixed the `files` list.
