### ISSUE TITLE
panic from lookup of non-existent account(s)

### ISSUE THREAD

**Issue by wilsonianb** [coilhq/tigerbeetle-node#4]
When I call `lookupAccounts` and none of my specified ids exist, I get the following:

```
debug: 746649394563965214: on_message: Header{ .checksum = 26737541277414919673681114361701047635, .checksum_body = 98081761841810822994326224503485043631, .nonce = 65988244422842662187530359719024616725, .clien = 90, .commit = 90, .offset = 0, .size = 128, .epoch = 0, .request = 1, .replica = 0, .command = Command.reply, .operation = Operation.lookup_accounts }
thread 379696 panic: index out of bounds
/opt/tigerbeetle-node/src/tigerbeetle/src/client.zig:419:98: 0x7f0a9456a9e2 in tigerbeetle.src.client.Batch(tigerbeetle.src.state_machine.Operation.lookup_accounts,1000).deliver (node)
/opt/tigerbeetle-node/src/tigerbeetle/src/client.zig:292:30: 0x7f0a94567c2c in tigerbeetle.src.client.BatchManager.deliver (node)
/opt/tigerbeetle-node/src/tigerbeetle/src/client.zig:102:35: 0x7f0a9456654f in tigerbeetle.src.client.Client.on_message (node)
...
```

Relatedly, when I call `lookupAccounts` and some of the specified ids exist, the returned `AccountLookupResult[]` only includes the existing `Account`s. Is `AccountLookupError` only expected to be returned if none of the specified accounts exist?

**Comment by jorangreef** [comment]
Thanks @wilsonianb for finding this and testing the PR already.

`lookupAccounts()` will only return matching accounts, because otherwise we would have multiple types in the batch response, and different result sizes and alignments. We will clarify this in the README.

**Comment by wilsonianb** [comment]
Thanks!

> `lookupAccounts()` will only return matching accounts, because otherwise we would have multiple types in the batch response, and different result sizes and alignments.

In that case, it sounds like `AccountLookupError` is never in play, and `lookupAccounts` could return `Promise<Account[]>` instead of `Promise<AccountLookupResult[]>`
